---
title: "eds-day4-session1-q"
format: html
editor: visual
---

## create vectors

```{r}
rain <- c(3,5, 10.1, 6)
rain_scaled <- 5* rain
```

## Create matrices

```{r}
my_values <- seq(from = 1, to = 10)
```

```{r}
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)
```

```{r}
my_matrix2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)
```

```{r}
matrix_a <- matrix(data = seq(from =2, to =5, length = 10), 
                   nrow = 2, 
                   ncol = 5, 
                   byrow = TRUE)
```

```{r}
my_matrix + matrix_a
```

## matrix multiplication

```{dogs = matrix(data = c(6, -3, 0, 2), nrow = 2, ncol = 2, byrow = TRUE)}

something <- rats %*% dogs
```

## Leslie Matrix Example

```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), 
                        nrow = 3,
                        ncol = 3,
                        byrow = TRUE)
insect_y0 <- c(1200, 700, 500)
```

find the population structure for each life stage at t = 1 year:

```{r}
insect_y1 = insect_leslie %*% insect_y0
insect_y2 = insect_leslie %*% insect_y1
```
